# use the Netlify Image CDN for image transformations
[[redirects]]
from = "/images/full/:path"
to = "/.netlify/images?url=/images/:path"
status = 200
[[redirects]]
from = "/images/thumb/:size/:path"
to = "/.netlify/images?w=:size&h=:size&fit=cover&url=/images/:path"
status = 200
